# Generated by Django 6.0.3 on 2026-03-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_camara', models.CharField(max_length=200, verbose_name='Nome da Câmara Municipal')),
                ('nome_solicitante', models.CharField(max_length=150, verbose_name='Nome do Solicitante')),
                ('cargo_solicitante', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail corporativo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Acesso',
                'verbose_name_plural': 'Solicitações de Acesso',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
