# Generated by Django 6.0.3 on 2026-04-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_camara_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Órgão')),
                ('abreviatura', models.CharField(max_length=50, verbose_name='Abreviatura / Sigla')),
                ('responsavel', models.CharField(max_length=150, verbose_name='Nome do Responsável')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informar')], default='M', max_length=1, verbose_name='Sexo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo do Responsável')),
                ('pronome_tratamento', models.CharField(choices=[('Excelentíssimo(a) Senhor(a)', 'Excelentíssimo(a) Senhor(a)'), ('Ilustríssimo(a) Senhor(a)', 'Ilustríssimo(a) Senhor(a)'), ('Ilustríssimo(a)', 'Ilustríssimo(a)'), ('Senhor(a)', 'Senhor(a)'), ('Vossa Excelência', 'Vossa Excelência'), ('Vossa Senhoria', 'Vossa Senhoria'), ('Reverendo(a)', 'Reverendo(a)'), ('Dom', 'Dom'), ('Padre', 'Padre'), ('Pastor(a)', 'Pastor(a)')], max_length=100, verbose_name='Pronome de Tratamento')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaos_externos', to='core.camara')),
            ],
            options={
                'verbose_name': 'Órgão Externo',
                'verbose_name_plural': 'Órgãos Externos',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('camara', 'nome'), name='unique_orgao_externo_por_camara')],
            },
        ),
    ]
