# Generated by Django 6.0.3 on 2026-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgaos_externos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgaoexterno',
            name='pronome_tratamento',
            field=models.CharField(choices=[('Vossa Senhoria / V.Sa.', 'Vossa Senhoria / V.Sa.'), ('Vossa Excelência / V.Ex.ª', 'Vossa Excelência / V.Ex.ª'), ('Vossa Magnificência / V.Mag.ª', 'Vossa Magnificência / V.Mag.ª'), ('Vossa Eminência / V.Ema.', 'Vossa Eminência / V.Ema.')], max_length=100, verbose_name='Pronome de Tratamento'),
        ),
    ]
