# Generated by Django 6.0.3 on 2026-04-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_camara_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('data_eleicao', models.DateField(verbose_name='Data da Eleição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
            ],
            options={
                'verbose_name_plural': 'Legislaturas',
                'ordering': ['-numero'],
                'indexes': [models.Index(fields=['camara'], name='legislatura_camara__6fea70_idx')],
                'constraints': [models.UniqueConstraint(fields=('camara', 'numero'), name='unique_legislatura_por_camara')],
            },
        ),
    ]
