# Generated by Django 6.0.3 on 2026-04-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_camara_email'),
        ('legislaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoLegislativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ORDINARIA', 'Ordinária'), ('EXTRAORDINARIA', 'Extraordinária'), ('SOLENE', 'Solene')], max_length=20, verbose_name='Categoria')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('data', models.DateField(verbose_name='Data')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
                ('legislatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='legislaturas.legislatura')),
            ],
            options={
                'verbose_name': 'Sessão Legislativa',
                'verbose_name_plural': 'Sessões Legislativas',
                'ordering': ['-data', '-numero'],
                'constraints': [models.UniqueConstraint(fields=('legislatura', 'numero', 'categoria'), name='unique_sessao_por_legislatura')],
            },
        ),
    ]
