# Generated by Django 6.0.3 on 2026-03-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
            ],
            options={
                'verbose_name': 'Numeração',
                'verbose_name_plural': 'Numerações',
                'unique_together': {('camara', 'autor', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('assunto', models.CharField(max_length=500)),
                ('corpo', models.TextField()),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20)),
                ('destinatario_nome', models.CharField(max_length=200, verbose_name='nome do destinatário')),
                ('destinatario_cargo', models.CharField(max_length=200, verbose_name='cargo do destinatário')),
                ('destinatario_orgao', models.CharField(max_length=200, verbose_name='órgão do destinatário')),
                ('destinatario_endereco', models.TextField(verbose_name='endereço do destinatário')),
                ('destinatario_pronome', models.CharField(help_text='Ex: Excelentíssimo(a), Ilustríssimo(a)', max_length=50, verbose_name='pronome de tratamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autores.autor')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['camara', '-criado_em'], name='oficios_ofi_camara__8c7c28_idx'), models.Index(fields=['camara', 'autor'], name='oficios_ofi_camara__4eefa7_idx'), models.Index(fields=['camara', 'status'], name='oficios_ofi_camara__39c821_idx')],
            },
        ),
    ]
