# Generated by Django 6.0.3 on 2026-03-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
