# Generated by Django 6.0.3 on 2026-03-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_options_alter_autor_cargo_and_more'),
        ('core', '0005_alter_camara_cidade'),
        ('oficios', '0002_alter_oficio_numero'),
        ('orgaos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numeracao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='numeracao',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgaos.orgao'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orgaos.orgao'),
        ),
        migrations.AlterUniqueTogether(
            name='numeracao',
            unique_together={('camara', 'orgao', 'autor', 'ano')},
        ),
        migrations.AddIndex(
            model_name='oficio',
            index=models.Index(fields=['camara', 'orgao'], name='oficios_ofi_camara__297c51_idx'),
        ),
    ]
