# Generated by Django 6.0.3 on 2026-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0003_alter_numeracao_unique_together_numeracao_orgao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='destinatario_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='cargo do destinatário'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='destinatario_endereco',
            field=models.TextField(blank=True, null=True, verbose_name='endereço do destinatário'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='destinatario_orgao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='órgão do destinatário'),
        ),
    ]
