# Generated by Django 6.0.3 on 2026-03-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_options_alter_autor_cargo_and_more'),
        ('oficios', '0004_alter_oficio_destinatario_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='coautores',
            field=models.ManyToManyField(blank=True, related_name='oficios_coautoria', to='autores.autor'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='e_conjunto',
            field=models.BooleanField(default=False, verbose_name='Ofício Conjunto'),
        ),
    ]
