# Generated by Django 6.0.3 on 2026-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0005_oficio_coautores_oficio_e_conjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('modificado', 'Modificado')], default='rascunho', max_length=20),
        ),
    ]
