# Generated by Django 6.0.3 on 2026-04-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_options_alter_autor_cargo_and_more'),
        ('oficios', '0006_alter_oficio_status'),
        ('sessoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='tipo',
            field=models.CharField(choices=[('livre', 'Ofício Livre'), ('encaminhamento', 'Encaminhamento de Proposições Aprovadas')], default='livre', max_length=30),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='assunto',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='corpo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='OficioEncaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacao', models.CharField(choices=[('maioria_simples', 'Maioria Simples'), ('maioria_qualificada', 'Maioria Qualificada'), ('unanimidade', 'Unanimidade')], max_length=50)),
                ('proposicao', models.CharField(help_text='Ex: Indicação n° 13', max_length=200, verbose_name='Proposição')),
                ('data_aprovacao', models.DateField(verbose_name='Data de Aprovação')),
                ('autor_proposicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_proposicao', to='autores.autor')),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamento', to='oficios.oficio')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessoes.sessaolegislativa')),
            ],
            options={
                'verbose_name': 'Ofício de Encaminhamento',
                'verbose_name_plural': 'Ofícios de Encaminhamento',
            },
        ),
    ]
