# Generated by Django 6.0.3 on 2026-04-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_options_alter_autor_cargo_and_more'),
        ('oficios', '0007_oficio_tipo_alter_oficio_assunto_alter_oficio_corpo_and_more'),
        ('core', '0007_numeracao'),  # Ensures Numeracao is created in core BEFORE deletion from oficios state
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='coautores',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_coautoria', to='autores.autor'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='e_conjunto',
            field=models.BooleanField(default=False, verbose_name='Documento Conjunto'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Numeracao',
                ),
            ],
            database_operations=[]  # Don't delete the table - it will be used by core.Numeracao
        ),
    ]
