# Generated by Django 6.0.3 on 2026-04-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0002_alter_autor_options_alter_autor_cargo_and_more'),
        ('core', '0007_numeracao'),
        ('orgaos', '0002_orgao_abreviatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('modificado', 'Modificado')], default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('e_conjunto', models.BooleanField(default=False, verbose_name='Documento Conjunto')),
                ('assunto', models.CharField(blank=True, max_length=500)),
                ('solicitacao', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autores.autor')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
                ('coautores', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_coautoria', to='autores.autor')),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orgaos.orgao')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
            },
        ),
    ]
