# Generated by Django 6.0.3 on 2026-03-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_camara_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['nome'],
                'unique_together': {('camara', 'nome')},
            },
        ),
    ]
