# Generated by Django 6.0.3 on 2026-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgaos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
