# Generated by Django 6.0.3 on 2026-03-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='logomarca_url',
        ),
        migrations.AddField(
            model_name='camara',
            name='logomarca',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Logomarca (Bytes)'),
        ),
    ]
