# Generated by Django 6.0.3 on 2026-03-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_camara_logomarca_url_camara_logomarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
    ]
