# Generated by Django 6.0.3 on 2026-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_camara_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='cidade',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
