# Generated by Django 6.0.3 on 2026-03-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_camara_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='cidade',
            field=models.CharField(max_length=200),
        ),
    ]
