# Generated by Django 6.0.3 on 2026-03-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_camara_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
