# Generated by Django 6.0.3 on 2026-04-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_options_alter_autor_cargo_and_more'),
        ('core', '0006_camara_email'),
        ('orgaos', '0002_orgao_abreviatura'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Numeracao',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo_documento', models.CharField(choices=[('oficio', 'Ofício'), ('indicacao', 'Indicação'), ('requerimento', 'Requerimento'), ('projeto_lei', 'Projeto de Lei'), ('parecer', 'Parecer'), ('portaria', 'Portaria')], default='oficio', max_length=20)),
                        ('ano', models.IntegerField()),
                        ('ultimo_numero', models.IntegerField(default=0)),
                        ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
                        ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
                        ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgaos.orgao')),
                    ],
                    options={
                        'verbose_name': 'Numeração',
                        'verbose_name_plural': 'Numerações',
                        'db_table': 'oficios_numeracao',
                        'unique_together': {('camara', 'orgao', 'autor', 'ano', 'tipo_documento')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE oficios_numeracao ADD COLUMN IF NOT EXISTS tipo_documento varchar(20) DEFAULT 'oficio' NOT NULL;
                    
                    DO $$ 
                    DECLARE 
                        constraint_name_val text;
                    BEGIN
                        SELECT conname INTO constraint_name_val
                        FROM pg_constraint
                        WHERE conrelid = 'oficios_numeracao'::regclass
                        AND contype = 'u' LIMIT 1;
                        
                        IF constraint_name_val IS NOT NULL THEN
                            EXECUTE 'ALTER TABLE oficios_numeracao DROP CONSTRAINT ' || constraint_name_val;
                        END IF;
                    END $$;
                    
                    ALTER TABLE oficios_numeracao ADD CONSTRAINT oficios_numeracao_uniq_doc UNIQUE NULLS NOT DISTINCT (camara_id, orgao_id, autor_id, ano, tipo_documento);
                    """
                ),
            ]
        ),
    ]
