# Generated by Django 6.0.3 on 2026-03-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('VER', 'Vereador')], default='VER', max_length=3)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camara')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'indexes': [models.Index(fields=['camara'], name='autores_aut_camara__652e00_idx')],
            },
        ),
    ]
