# Generated by Django 6.0.3 on 2026-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
        ('core', '0003_camara_cep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='cargo',
            field=models.CharField(choices=[('PR', 'Presidente'), ('VP', 'Vice-Presidente'), ('1S', '1º Secretário'), ('2S', '2º Secretário'), ('VER', 'Vereador')], default='VER', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(fields=('camara', 'nome', 'cargo'), name='unique_autor_por_camara'),
        ),
    ]
